[package]
name = "charp2p-mls"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
charp2p-core = { path = "../charp2p-core" }
openmls.workspace = true
openmls_memory_storage = "0.6.0"
openmls_rust_crypto.workspace = true
openmls_traits.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[dev-dependencies]
openmls_basic_credential.workspace = true
